export const msgCode = {
  noPermission: { code: -403, msg: "没有权限" },
  expiredToken: { code: -203, msg: "token过期，请重新登录" },
  invalidToken: { code: -202, msg: "token无效，请重新登录" },
  invalidRequest: { code: -201, msg: "无效请求" },
  loginExpire: { code: -200, msg: "登录过期，请重新登录" },
  invalidUser: { code: -101, msg: "用户名或密码错误" },
  loginError: { code: -100, msg: "登录失败" },
  exception: { code: -1, msg: "请求异常" },
  error: { code: 0, msg: "未知错误" },
  success: { code: 200, msg: "操作成功", data: [] || {} },
  parmasError: { code: 10001, msg: "参数错误" },
  successWithoutData: { code: 10002, msg: "请求成功，无数据" },
  existsUser: { code: 10003, msg: "已经存在相同的用户名" },
  existsRole: { code: 10004, msg: "已经存在相同的角色" },
  existsMenu: { code: 10005, msg: "已经存在相同的菜单" },
  existsGame: { code: 10006, msg: "已经存在相同的游戏" },
  existsBanner: { code: 10007, msg: "已经存在相同的banner名称" },
  existsArticle: { code: 10008, msg: "标题重复" },
  existsTeam: { code: 10009, msg: "队伍已存在" },
  existsActicityLog: { code: 10010, msg: "已选择队伍" },
  existsSerise: { code: 10011, msg: "赛事已存在" },
  existsGuessing: { code: 10012, msg: "竞猜已存在" }
};
export default msgCode;
